 
 CURRENTLY NOT MANY TESTS, WILL CONTINUE TO ADD MORE
 SOURCE CODE FILES DONT HAVE ANY EXTENSION, SHOULD BE ABLE TO Make AND THEN ./compiler <src_file>
 CHECK EMPLEX AND LEXER FILE FOR SYNTAX RULES 
